config/routes.rb
Rails.application.routes.draw do
  resources :parts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/part.rb
class Part
  include Mongoid::Document
  include Mongoid::Timestamps
  field :part_num, type: String
  field :short_name, type: String
  field :status, type: String
  field :location, type: String
  field :min_quantity, type: Integer
  field :total_on_hand, type: Integer
  field :unit, type: String
  field :inventory_history, type: Hash, default: {}
  field :backstock_history, type: Hash, default: {}
  field :price_history, type: Hash, default: {}
  field :supplier_history, type: Hash, default: {}
  field :purchase_link_history, type: Hash, default: {}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]

  # GET /parts or /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1 or /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts or /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to part_url(@part), notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1 or /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to part_url(@part), notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1 or /parts/1.json
  def destroy
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:part_num, :short_name, :status, :location, :min_quantity, :total_on_hand, :unit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Physcompdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parts/_form.html.erb
<%= form_with(model: part) do |form| %>
  <% if part.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :part_num, style: "display: block" %>
    <%= form.text_field :part_num %>
  </div>

  <div>
    <%= form.label :short_name, style: "display: block" %>
    <%= form.text_field :short_name %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :min_quantity, style: "display: block" %>
    <%= form.number_field :min_quantity %>
  </div>

  <div>
    <%= form.label :total_on_hand, style: "display: block" %>
    <%= form.number_field :total_on_hand %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<div id="<%= dom_id part %>">
  <p>
    <strong>Part num:</strong>
    <%= part.part_num %>
  </p>

  <p>
    <strong>Short name:</strong>
    <%= part.short_name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= part.status %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= part.location %>
  </p>

  <p>
    <strong>Min quantity:</strong>
    <%= part.min_quantity %>
  </p>

  <p>
    <strong>Total on hand:</strong>
    <%= part.total_on_hand %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= part.unit %>
  </p>

</div>

app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to "Show this part", @part %> |
  <%= link_to "Back to parts", parts_path %>
</div>

app/views/parts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Parts</h1>

<div id="parts">
  <% @parts.each do |part| %>
    <%= render part %>
    <p>
      <%= link_to "Show this part", part %>
    </p>
  <% end %>
</div>

<%= link_to "New part", new_part_path %>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to "Back to parts", parts_path %>
</div>

app/views/parts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @part %>

<div>
  <%= link_to "Edit this part", edit_part_path(@part) %> |
  <%= link_to "Back to parts", parts_path %>

  <%= button_to "Destroy this part", @part, method: :delete %>
</div>